
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 15 20:15:44 CEST 2018
//----------------------------------------------------

package fr.esisar.compilation.syntaxe;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CROCH_OUVR = 44;
  public static final int MULT = 36;
  public static final int SUP_EGAL = 33;
  public static final int EGAL = 30;
  public static final int INF_EGAL = 32;
  public static final int POINT_VIRGULE = 43;
  public static final int VIRGULE = 42;
  public static final int ARRAY = 7;
  public static final int DIV_REEL = 37;
  public static final int FOR = 14;
  public static final int WRITE = 27;
  public static final int NOT = 18;
  public static final int AND = 6;
  public static final int INF = 28;
  public static final int OR = 21;
  public static final int AFFECT = 46;
  public static final int PAR_OUVR = 38;
  public static final int DIV = 9;
  public static final int BEGIN = 8;
  public static final int PLUS = 34;
  public static final int IF = 15;
  public static final int CONST_ENT = 3;
  public static final int OF = 20;
  public static final int EOF = 0;
  public static final int CROCH_FERM = 45;
  public static final int error = 1;
  public static final int PROGRAM = 22;
  public static final int MOINS = 35;
  public static final int NULL = 19;
  public static final int MOD = 16;
  public static final int CONST_REEL = 4;
  public static final int IDF = 2;
  public static final int DEUX_POINTS = 41;
  public static final int ELSE = 12;
  public static final int POINT = 47;
  public static final int READ = 23;
  public static final int TO = 25;
  public static final int NEW_LINE = 17;
  public static final int WHILE = 26;
  public static final int DOUBLE_POINT = 40;
  public static final int THEN = 24;
  public static final int SUP = 29;
  public static final int END = 13;
  public static final int DIFF = 31;
  public static final int CONST_CHAINE = 5;
  public static final int DOWNTO = 11;
  public static final int PAR_FERM = 39;
  public static final int DO = 10;
}

